### ISSUE TITLE
Clarify data paths for time series

### ISSUE THREAD

**Issue by Eghelakpo** [appliedepi/epiRhandbook_eng#62] opened 2021-11-01 16:18 UTC
Weather data is missing. The codes chunks for Fitting regressions are returning error messages.

**Comment by aspina7** [comment] 2021-11-01 16:33
hello @Eghelakpo - thanks very much for your post, datasets should be available if you follow the steps in ["2.2 Download data to follow along"](https://epirhandbook.com/en/download-handbook-and-data.html#download-data-to-follow-along). Specifically also see the [subpoint](https://epirhandbook.com/en/download-handbook-and-data.html#data_outbreak) on time series data used. 
Alternatively you could make an account with Copernicus and download the climate data directly as described on the [time series page ](https://epirhandbook.com/en/time-series-and-outbreak-detection.html#download-climate-data)
hope this is helpful, please let us know if not!

**Comment by Eghelakpo** [comment] 2021-11-01 17:44
@ aspina7, many thanks for your response. I got the Copernicus data as individual year data and combined them into a dataframe as below:
  weather <- as.data.frame(c(
     weather1, 
     weather2, 
     weather3, 
     weather4,
     weather5,
     weather6,
     weather7,
     weather8,
     weather9
     ))


But this chunk of code below is not working:

## change to a data frame 
   temp_data <- as_tibble(data) %>% 
     ## add in variables and correct units
     mutate(
       ## create an calendar week variable 
       epiweek = tsibble::yearweek(time), 
       ## create a date variable (start of calendar week)
       date = as.Date(epiweek),
       ## change temperature from kelvin to celsius
       t2m = set_units(t2m, celsius), 
       ## change precipitation from metres to millimetres 
       tp  = set_units(tp, mm)) %>% 
     ## group by week (keep the date too though)
     group_by(epiweek, date) %>% 
     ## get the average per week
     summarise(t2m = as.numeric(mean(t2m)), 
               tp = as.numeric(mean(tp)))

**Comment by Eghelakpo** [comment] 2021-11-01 17:51
Please I have been unable to figure out the reason for the error in the code below:

counts$fourier <- counts %>% select(counts, epiweek, case_int) %>% 
    fourier(K = 1)
  
Error in select(., counts, epiweek, case_int) : 
  unused arguments (counts, epiweek, case_int)

Its not allowing to make progress .

**Comment by aspina7** [comment] 2021-11-01 18:27
>`weather <- as.data.frame(c( weather1, weather2, weather3, weather4, weather5, weather6, weather7, weather8, weather9 ))
`
This will be where your issue arises. If you follow the code in [load climate data](https://epirhandbook.com/en/time-series-and-outbreak-detection.html#load-climate-data), specifically the chunk below, then the following chunks should also work. 

```
## define path to weather folder 
file_paths <- list.files(
  here::here("data", "time_series", "weather"), # replace with your own file path 
  full.names = TRUE)

## only keep those with the current name of interest 
file_paths <- file_paths[str_detect(file_paths, "germany")]

## read in all the files as a stars object 
data <- stars::read_stars(file_paths) 
```

**Comment by Eghelakpo** [comment] 2021-11-02 06:51
@ Alex, Many thanks for your assistance. I actually downloaded the whole EpiR handbook datasets. But I could not find any data labelled "time_series" and "weather". I hope I am not using an older version of the EpiR handbook. So the code chunk you illustrated above is giving error message.

**Comment by akarsteve** [comment] 2021-11-03 00:14
Alex could you please check why the code below is giving this error message?

 ## add in fourier terms using the epiweek and case_int variabless
  counts$fourier <- select(counts, epiweek, case_int) %>% 
    fourier(K = 1)

Error:
Error in select(counts, epiweek, case_int) : 
  unused arguments (epiweek, case_int)

**Comment by akarsteve** [comment] 2021-11-03 00:43
Still on importing the climate data, see my chunk of code below with the error message:

 # import weather data
   
   ## define path to weather folder 
   file_paths <- list.files(
     here::here("D:/Backup/Documents/R_Scripts/EpiR Handbook data", "time_series", "weather"), # replace with your own file path 
     full.names = TRUE)
   ## only keep those with the current name of interest 
   file_paths <- file_paths[str_detect(file_paths, "germany_weather")]
   
   ## read in all the files as a stars object 
   data <- stars::read_stars(file_paths)


Error message:
Error in if (is.function(.x) || !np || any(sapply(prefixes, has_prefix,  : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In any(sapply(prefixes, has_prefix, x = .x)) :
  coercing argument of type 'list' to logical


Can you help identify the cause of the trouble please?

**Comment by akarsteve** [comment] 2021-11-03 01:46
Here is another troubel under the Outbreak Detection Section:

 ## add in missing weeks till end of year 
  counts <- counts %>%
    ## group by the region
    group_by_key() %>%
    ## for each group add rows from the highest epiweek to the end of year
    group_modify(~add_row(.,
                          epiweek = seq(max(.$epiweek) + 1, 
                                        end_date,
                                        by = 1)))
Error message:
Error in seq.int(0, to0 - from, by) : wrong sign in 'by' argument

**Comment by akarsteve** [comment] 2021-11-03 01:51
I suggest the Time Series and Outbreak Detection Chapter should be reviewed. It seems to be having so many issues.

**Comment by akarsteve** [comment] 2021-11-03 03:15
As for the section on Surveillance package, I got an error with the huge code chunk below:


## define the model you want to fit (negative binomial) 
  model <- glm_nb_model(
    ## set number of cases as outcome of interest
    case_int ~
      ## use epiweek to account for the trend
      epiweek +
      ## use the furier terms to account for seasonality
      fourier + 
      ## add in whether in the pre- or post-period 
      intervention + 
      ## add in the time post intervention 
      time_post
  )
  
  ## fit your model using the counts dataset
  fitted_model <- trending::fit(model, counts)
  
  ## calculate confidence intervals and prediction intervals 
  observed <- predict(fitted_model, simulate_pi = FALSE)
  
  
  
  ## show estimates and percentage change in a table
  fitted_model %>% 
    ## extract original negative binomial regression
    get_model() %>% 
    ## get a tidy dataframe of results
    tidy(exponentiate = TRUE, 
         conf.int = TRUE) %>% 
    ## only keep the intervention value 
    filter(term == "intervention") %>% 
    ## change the IRR to percentage change for estimate and CIs 
    mutate(
      ## for each of the columns of interest - create a new column
      across(
        all_of(c("estimate", "conf.low", "conf.high")), 
        ## apply the formula to calculate percentage change
        .f = function(i) 100 * (i - 1), 
        ## add a suffix to new column names with "_perc"
        .names = "{.col}_perc")
    ) %>% 
    ## only keep (and rename) certain columns 
    select("IRR" = estimate, 
           "95%CI low" = conf.low, 
           "95%CI high" = conf.high,
           "Percentage change" = estimate_perc, 
           "95%CI low (perc)" = conf.low_perc, 
           "95%CI high (perc)" = conf.high_perc,
           "p-value" = p.value)


Error message:
Error in select(., IRR = estimate, `95%CI low` = conf.low, `95%CI high` = conf.high,  : 
  unused arguments (IRR = estimate, `95%CI low` = conf.low, `95%CI high` = conf.high, `Percentage change` = estimate_perc, `95%CI low (perc)` = conf.low_perc, `95%CI high (perc)` = conf.high_perc, `p-value` = p.value)

Please I really need to resolve these issues. The codes under the Time Series and Outbreak Detection are very important for my PhD study. I feel so frustrated with the many errors right now. Please help!!!!

**Comment by aspina7** [comment] 2021-11-03 09:03
Dear both - many thanks for pointing out these issues. 
I know errors can be frustrating but please remember that everyone is currently working on this project as volunteers! 

I believe the issue that you are both facing is with importing the data and having it in the correct format for the code to run. 

I will post example code in this comment and then reply to your individual comments separately to point out what to focus on. **Note**: for this example I have a folder on my desktop called `data`, which contains a folder called `time_series` and in that folder there is another one called `weather`. 

If your data does not look like the output below then the rest of your code will not work. 

``` r
## install our package to download the handbook and datasets 
pacman::p_install_gh("appliedepi/epirhandbook")
#> Skipping install of 'epirhandbook' from a github remote, the SHA1 (d777eb75) has not changed since last install.
#>   Use `force = TRUE` to force installation
#> 
#> The following packages were installed:
#> epirhandbook

## load necessary packages

pacman::p_load(
  ### NOTE: THESE TWO PACKAGES ARE NECESSARY (BUT NOT LISTED IN THE HANDBOOK)
               epirhandbook, # download datasets
               stringr,      # work with strings (file paths)
  ### the remaining packages listed here are listed in the handbook
               rio,          # File import
               here,         # File locator
               tidyverse,    # data management + ggplot2 graphics
               tsibble,      # handle time series datasets
               slider,       # for calculating moving averages
               imputeTS,     # for filling in missing values
               feasts,       # for time series decomposition and autocorrelation
               forecast,     # fit sin and cosin terms to data (note: must load after feasts)
               trending,     # fit and assess models 
               tmaptools,    # for getting geocoordinates (lon/lat) based on place names
               ecmwfr,       # for interacting with copernicus sateliate CDS API
               stars,        # for reading in .nc (climate data) files
               units,        # for defining units of measurement (climate data)
               yardstick,    # for looking at model accuracy
               surveillance  # for aberration detection
)


## define the path to folder where you are working from 
file_folder <- here::here("data", "time_series")


########### Downloading data 

## download a specific file into a folder on your computer
get_data("campylobacter_germany.xlsx", path = file_folder)
get_data("germany_weather2002.nc", path = str_c(file_folder, "/weather"))
get_data("germany_weather2003.nc", path = str_c(file_folder, "/weather"))
get_data("germany_weather2004.nc", path = str_c(file_folder, "/weather"))
get_data("germany_weather2005.nc", path = str_c(file_folder, "/weather"))
get_data("germany_weather2006.nc", path = str_c(file_folder, "/weather"))
get_data("germany_weather2007.nc", path = str_c(file_folder, "/weather"))
get_data("germany_weather2008.nc", path = str_c(file_folder, "/weather"))
get_data("germany_weather2009.nc", path = str_c(file_folder, "/weather"))
get_data("germany_weather2010.nc", path = str_c(file_folder, "/weather"))
get_data("germany_weather2011.nc", path = str_c(file_folder, "/weather"))



############ Importing counts data 

## import the counts into R
counts <- rio::import(str_c(file_folder, "/campylobacter_germany.xlsx"))

## ensure the date column is in the appropriate format
counts$date <- as.Date(counts$date)

## create a calendar week variable 
## fitting ISO definitons of weeks starting on a monday
counts <- counts %>% 
  mutate(epiweek = yearweek(date, week_start = 1))


########### Importing weather data 


## define path to weather folder 
file_paths <- list.files(
  str_c(file_folder, "/weather"), # replace with your own file path 
  full.names = TRUE)

## only keep those with the current name of interest 
file_paths <- file_paths[str_detect(file_paths, "germany")]

## read in all the files as a stars object 
data <- stars::read_stars(file_paths)


## change to a data frame 
temp_data <- as_tibble(data) %>% 
  ## add in variables and correct units
  mutate(
    ## create an calendar week variable 
    epiweek = tsibble::yearweek(time), 
    ## create a date variable (start of calendar week)
    date = as.Date(epiweek),
    ## change temperature from kelvin to celsius
    t2m = set_units(t2m, celsius), 
    ## change precipitation from metres to millimetres 
    tp  = set_units(tp, mm)) %>% 
  ## group by week (keep the date too though)
  group_by(epiweek, date) %>% 
  ## get the average per week
  summarise(t2m = as.numeric(mean(t2m)), 
            tp = as.numeric(mean(tp)))


############# view data 
head(counts)

        date case  epiweek
1 2001-12-31  514 2002 W01
2 2002-01-07  913 2002 W02
3 2002-01-14 1023 2002 W03
4 2002-01-21  887 2002 W04
5 2002-01-28  815 2002 W05
6 2002-02-04  792 2002 W06

head(temp_data)

# A tibble: 6 x 4
# Groups:   epiweek [6]
   epiweek date         t2m     tp
    <week> <date>     <dbl>  <dbl>
1 2002 W01 2001-12-31 -7.31 0.0153
2 2002 W02 2002-01-07 -1.92 0.0149
3 2002 W03 2002-01-14 -1.19 0.0403
4 2002 W04 2002-01-21  6.38 0.161 
5 2002 W05 2002-01-28  8.92 0.0379
6 2002 W06 2002-02-04  6.98 0.0921

```

<sup>Created on 2021-11-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by aspina7** [comment] 2021-11-03 09:12
> file_paths <- list.files( **here::here("D:/Backup/Documents/R_Scripts/EpiR Handbook data"**, "time_series", "weather"), # replace with your own file path full.names = TRUE)

@akarsteve the issue is how you are defining your file-path. You need to make sure how you define `here::here()` actually points to the place where your data is saved! You dont need to specify the harddrive with `D:/` because `here::here()` detects what folder you are in. 
Please review the [Chapter 7: importing and export](https://epirhandbook.com/en/import-and-export.html#file-paths), specifically subheading 7.3 and 7.4 on the `here` package and `filepaths`. 

For more explanation see part of this [presentation](https://www.youtube.com/watch?v=nxBTDfJ_neE&t=1565s)

**Comment by aspina7** [comment] 2021-11-03 09:15
> @ Alex, Many thanks for your assistance. I actually downloaded the whole EpiR handbook datasets. But I could not find any data labelled "time_series" and "weather". I hope I am not using an older version of the EpiR handbook. So the code chunk you illustrated above is giving error message.

@Eghelakpo apologies - this needs to be clarified in the handbook page if you see from my [example above](https://github.com/appliedepi/epiRhandbook_eng/issues/62#issuecomment-958759744), the data files are actually called "germany_weather2002.nc" (for the 2002 data).

**Comment by akarsteve** [comment] 2021-11-04 09:58
@ Alex, many thanks for the clarification on data importing. I have been able to overcome the data importing issues. Could you please look at the code on data joining? The select() seems to be an issue:

## left join so that we only have the rows already existing in counts
## drop the date variable from temp_data (otherwise is duplicated)
counts <- left_join(counts, 
                    select(temp_data, -date),
                    by = "epiweek")

Error: 
Error in select(temp_data, -date) : unused argument (-date)

**Comment by akarsteve** [comment] 2021-11-04 11:01
Here is the code that finally worked for me:


  ## left join so that we only have the rows already existing in counts
  ## drop the date variable from temp_data (otherwise is duplicated)
  
  count_sub <- left_join(counts, 
                  temp_data, -date,
                      by = "epiweek")
  count_sub = subset(count_sub, select = -c(date.x, date.x.x, date.x.x.x, date.y, case, case_miss,tp,  tp.x, tp.x.x, tp.x.x.x, tp.y, tp.y.y, tp.y.y.y, ma_4wk, t2m.x, t2m.x.x, t2m.x.x.x, t2m.y, t2m.y.y, t2m.y.y.y))
  
  flextable::qflextable(count_sub)

**Comment by aspina7** [comment] 2021-11-04 14:07
@akarsteve - `select()` is not the issue here. It is your dataset. 
The reason you have all of those x's and y's after variable names is that you have merged the same datasets together multiple times. 
Start fresh and follow the code that I shared for importing. 
Ensure that your dataset looks the same as I have posted above - and there should not be an issue.

**Comment by akarsteve** [comment] 2021-11-05 03:02
Alex could please check if my Fourier code is okay?


counts$fourier <- subset(counts, select = c(epiweek, case_int)) %>% 
  fourier(K = 1)
counts$fourier

**Comment by aspina7** [comment] 2021-11-05 04:47
Sorry Steven - at the moment we don't have capacity to check people's code unless it is the same as the handbook example and is throwing errors. 
We are in the process of building that capacity so please bare with us.

**Comment by akarsteve** [comment] 2021-11-05 06:30
Thanks Alex. No prob. Please the code below is where I currently stuck:

## define the model you want to fit (negative binomial) 
model <- glm_nb_model(
  ## set number of cases as outcome of interest
  case_int ~
    ## use epiweek to account for the trend
    epiweek +
    ## use the fourier terms to account for seasonality
    fourier + 
    ## use the temperature lagged by four weeks 
    t2m_lag4
)

## fit your model using the counts dataset
fitted_model <- trending::fit(model, counts)

## calculate confidence intervals and prediction intervals 
observed <- predict(fitted_model, simulate_pi = FALSE)

Error Message:
Error: Not supported for tsibble.
i Please use `dplyr::bind_cols()` instead.
Run `rlang::last_error()` to see where the error occurred.

I can't figure out exactly what went wrong. I meticulously followed the steps you described previously.

**Comment by akarsteve** [comment] 2021-11-05 08:42
Hello Alex, this is to express my profound gratitude to you and the rest of the team for preparing the EpiR Handbook and the github  forum to address matters arising from users. I must say the handbook is fantastically fit-for-purpose and has made learning R so easy for epidemiologists around the world. I believe with time the issues raised about the handbook would be adequately addressed. Its a great start at least.

**Comment by akarsteve** [comment] 2021-11-06 08:32
@ Alex, I am trying to download weather data in Vietnam from 2016 - 2021. It just kept running and running and restarts after an hour. I can't decipher where the issue is: 


 
### Download climate dtata
 ## retrieve location coordinates
 coords <- geocode_OSM("Vietnam", geometry = "point")
 
 ## pull together long/lats in format for ERA-5 querying (bounding box) 
 ## (as just want a single point can repeat coords)
 request_coords <- str_glue_data(coords$coords, "{y}/{x}/{y}/{x}")
 
 
 ## Pulling data modelled from copernicus satellite (ERA-5 reanalysis)
 ## https://cds.climate.copernicus.eu/cdsapp#!/software/app-era5-explorer?tab=app
 ## https://github.com/bluegreen-labs/ecmwfr
 
 ## set up key for weather data 
 wf_set_key(user = "108706",
            key = "bd3fa5b0-4b9e-4126-9545-00b0aaaaa63d",
            service = "cds") 
 
 ## run for each year of interest (otherwise server times out)
 for (i in 2016:2021) {
   
   ## pull together a query 
   ## see here for how to do: https://bluegreen-labs.github.io/ecmwfr/articles/cds_vignette.html#the-request-syntax
   ## change request to a list using addin button above (python to list)
   ## Target is the name of the output file!!
   request <- request <- list(
     product_type = "reanalysis",
     format = "netcdf",
     variable = c("2m_temperature", "total_precipitation"),
     year = c(i),
     month = c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"),
     day = c("01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12",
             "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24",
             "25", "26", "27", "28", "29", "30", "31"),
     time = c("00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00",
              "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00",
              "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00"),
     area = request_coords,
     dataset_short_name = "reanalysis-era5-single-levels",
     target = paste0("vietnam_weather", i, ".nc")
   )
   
   ## download the file and store it in the current working directory
   file <- wf_request(user     = "108706",  # user ID (for authentication)
                      request  = request,  # the request
                      transfer = TRUE,     # download the file
                      path     = here::here("C:/Users/Akarstephen/Desktop/R_Scripts", "data_t2m")) ## path to save the data
 }
 
 
 
 I will appreciate it if you could advice please!

**Comment by akarsteve** [comment] 2021-11-06 08:38
@aspina7 ,   Please I substituted ARI data for the counts data as in the code chunk below but I kept getting error. I have been unable to identify where the trouble is. See the error message below the code please.


   pacman::p_load(forecast)
   
   ## define the model you want to fit (negative binomial) 
   model <- glm_nb_model(
     ## set number of cases as outcome of interest
     case_counts$case_int ~
       ## use epiweek to account for the trend
       case_counts$epiweek +
       ## use the fourier terms to account for seasonality
       fourier)
   
  
   pacman::p_load(trending)
   ## fit your model using the counts dataset
   fitted_model <- trending::fit(model, case_counts)
   
   ## calculate confidence intervals and prediction intervals 
   observed <- predict(fitted_model, simulate_pi = TRUE)
   
   ## plot your regression 
   ggplot(data = observed, aes(x = as.Date(epiweek))) + 
     ## add in a line for the model estimate
     geom_line(aes(y = estimate),
               col = "Red") + 
     ## add in a band for the prediction intervals 
     geom_ribbon(aes(ymin = lower_pi, 
                     ymax = upper_pi), 
                 alpha = 0.25) + 
     ## add in a line for your observed case counts
     geom_line(aes(y = case_int), 
               col = "royalblue") + 
     ## make a traditional plot (with black axes and white background)
     theme_classic() + 
     
     
     scale_x_date(date_labels="%Y-Wk %W",            # date label format show month 
                  date_breaks="2 month",         # date labels on 1st of each month
                  expand=c(0,0)) +             # remove excess space
     scale_y_continuous(
       expand  = c(0,0))+                      # remove excess space below x-axis
     
     labs(
       x = "Epiweek",
       y = "Weekly incidence",
       title = "Fitted model of hospitalized pediatric ARI cases in Vietnam, 2016 - 2021"
     ) +
     
     theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))   +   
     
     theme(legend.title = element_text(face = "bold")) +               
     
     theme(legend.title = element_text(colour="black", size=10, face="bold")) +
     theme(legend.position="bottom") +
     
     # adjust bold face, and caption position
     theme(
       axis.title = element_text(size = 6, face = "bold"),    # axis titles larger and bold
       axis.text = element_text(size = 5, face = "bold"),     # axis text size and bold
       plot.caption = element_text(hjust = 0, face = "italic"))  # move caption to left 
   


   ## calculate the residuals 
   observed <- observed %>% 
     mutate(resid = residuals(fitted_model$fitted_model, type = "response"))
   
   ## are the residuals fairly constant over time (if not: outbreaks? change in practice?)
   observed %>%
     ggplot(aes(x = epiweek, y = resid)) +
     geom_line() +
     geom_point() + 
     labs(x = "epiweek", y = "Residuals")
   

Error Message:

 ## fit your model using the counts dataset
>    fitted_model <- trending::fit(model, case_counts)
Warning messages:
1: In dpois(y, mu, log = TRUE) : non-integer x = 16.400000
2: In dpois(y, mu, log = TRUE) : non-integer x = 12.800000
3: In dpois(y, mu, log = TRUE) : non-integer x = 9.200000
4: In dpois(y, mu, log = TRUE) : non-integer x = 5.600000
5: In dpois(y, mu, log = TRUE) : non-integer x = 12.800000
6: In dpois(y, mu, log = TRUE) : non-integer x = 12.600000
7: In dpois(y, mu, log = TRUE) : non-integer x = 12.400000
8: In dpois(y, mu, log = TRUE) : non-integer x = 12.200000
> 

## calculate confidence intervals and prediction intervals 
>    observed <- predict(fitted_model, simulate_pi = TRUE)
Error: Can't subset columns that don't exist.
x Column `case_counts` doesn't exist.
Backtrace:
  1. stats::predict(fitted_model, simulate_pi = TRUE)
  2. trending:::predict.trending_model_fit(fitted_model, simulate_pi = TRUE)
  3. object$predict(...)
  7. tibble:::`[.tbl_df`(data, all.vars(formula(model)))
  8. tibble:::vectbl_as_col_location(...)
 11. vctrs::vec_as_location(j, n, names)
 13. vctrs:::stop_subscript_oob(...)
 14. vctrs:::stop_subscript(...)
>

**Closed** 2024-09-28 15:49 UTC
Labels: bug, question, for next revision
